/* -------------------- AUTHENTICATION -------------------- */
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

/* -------------------- ADMIN -------------------- */
// Dashboard
export const FETCH_DASHBOARD_PENDING = "FETCH_DASHBOARD_PENDING";
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_FAILURE = "FETCH_DASHBOARD_FAILURE";

// Drug cateogry
export const CREATE_DRUG_CATEGORY_PENDING = "CREATE_DRUG_CATEGORY_PENDING";
export const CREATE_DRUG_CATEGORY_SUCCESS = "CREATE_DRUG_CATEGORY_SUCCESS";
export const CREATE_DRUG_CATEGORY_FAILURE = "CREATE_DRUG_CATEGORY_FAILURE";

export const FETCH_DRUG_CATEGORIES_PENDING = "FETCH_DRUG_CATEGORIES_PENDING";
export const FETCH_DRUG_CATEGORIES_SUCCESS = "FETCH_DRUG_CATEGORIES_SUCCESS";
export const FETCH_DRUG_CATEGORIES_FAILURE = "FETCH_DRUG_CATEGORIES_FAILURE";

export const FETCH_DRUG_CATEGORY_DETAILS_PENDING = "FETCH_DRUG_CATEGORY_DETAILS_PENDING";
export const FETCH_DRUG_CATEGORY_DETAILS_SUCCESS = "FETCH_DRUG_CATEGORY_DETAILS_SUCCESS";
export const FETCH_DRUG_CATEGORY_DETAILS_FAILURE = "FETCH_DRUG_CATEGORY_DETAILS_FAILURE";

export const UPDATE_DRUG_CATEGORY_PENDING = "UPDATE_DRUG_CATEGORY_PENDING";
export const UPDATE_DRUG_CATEGORY_SUCCESS = "UPDATE_DRUG_CATEGORY_SUCCESS";
export const UPDATE_DRUG_CATEGORY_FAILURE = "UPDATE_DRUG_CATEGORY_FAILURE";

export const DELETE_DRUG_CATEGORY_PENDING = "DELETE_DRUG_CATEGORY_PENDING";
export const DELETE_DRUG_CATEGORY_SUCCESS = "DELETE_DRUG_CATEGORY_SUCCESS";
export const DELETE_DRUG_CATEGORY_FAILURE = "DELETE_DRUG_CATEGORY_FAILURE";

// Drug unit
export const FETCH_DRUG_UNIT_PENDING = "FETCH_DRUG_UNIT_PENDING";
export const FETCH_DRUG_UNIT_SUCCESS = "FETCH_DRUG_UNIT_SUCCESS";
export const FETCH_DRUG_UNIT_FAILURE = "FETCH_DRUG_UNIT_FAILURE";

// Drug route
export const FETCH_DRUG_ROUTE_PENDING = "FETCH_DRUG_ROUTE_PENDING";
export const FETCH_DRUG_ROUTE_SUCCESS = "FETCH_DRUG_ROUTE_SUCCESS";
export const FETCH_DRUG_ROUTE_FAILURE = "FETCH_DRUG_ROUTE_FAILURE";

// Drug dosage form
export const FETCH_DRUG_DOSAGE_FORM_PENDING = "FETCH_DRUG_DOSAGE_FORM_PENDING";
export const FETCH_DRUG_DOSAGE_FORM_SUCCESS = "FETCH_DRUG_DOSAGE_FORM_SUCCESS";
export const FETCH_DRUG_DOSAGE_FORM_FAILURE = "FETCH_DRUG_DOSAGE_FORM_FAILURE";

// Drug
export const FETCH_DRUG_PENDING = "FETCH_DRUG_PENDING";
export const FETCH_DRUG_SUCCESS = "FETCH_DRUG_SUCCESS"
export const FETCH_DRUG_FAILURE = "FETCH_DRUG_FAILURE";

// Drug instruction
export const FETCH_DRUG_INSTRUCTION_PENDING = "FETCH_DRUG_INSTRUCTION_PENDING";
export const FETCH_DRUG_INSTRUCTION_SUCCESS = "FETCH_DRUG_INSTRUCTION_SUCCESS";
export const FETCH_DRUG_INSTRUCTION_FAILURE = "FETCH_DRUG_INSTRUCTION_FAILURE";

/* -------------------- USER -------------------- */
// Profile
export const GET_PROFILE_PENDING = "GET_PROFILE_PENDING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

// Disease category
export const FETCH_DISEASE_CATEGORIES_PENDING = "FETCH_DISEASE_CATEGORIES_PENDING";
export const FETCH_DISEASE_CATEGORIES_SUCCESS = "FETCH_DISEASE_CATEGORIES_SUCCESS";
export const FETCH_DISEASE_CATEGORIES_FAILURE = "FETCH_DISEASE_CATEGORIES_FAILURE";

// Disease
export const FETCH_DISEASES_PENDING = "FETCH_DISEASES_PENDING";
export const FETCH_DISEASES_SUCCESS = "FETCH_DISEASES_SUCCESS";
export const FETCH_DISEASES_FAILURE = "FETCH_DISEASES_FAILURE";

/* -------------------- PATIENT -------------------- */